from rank_fragments import *
from gen_data_util import *

import argparse
import glob
import json
import pandas

import matplotlib.pyplot as plt
import traceback
import multiprocessing

class drug_fragment_selection:
    def __init__(self, first_fragment_index, num_fragments, drug_smiles):
        self.first_fragment_index = first_fragment_index
        self.num_fragments = num_fragments
        self.drug_smiles = drug_smiles

def sum_skip_none(l: list[float]) -> float:
    sum = 0
    for v in l:
        if v == None:
            continue
        sum += v
    return sum

def len_skip_none(l: list) -> int:
    sum = 0
    for v in l:
        if v != None:
            sum += 1
    return sum

def setup_process(argsa, fragment_smilesa, drug_fragment_pairsa, mutexa):
    global args
    args = argsa
    global fragment_smiles
    fragment_smiles = fragment_smilesa
    global drug_fragment_pairs
    drug_fragment_pairs = drug_fragment_pairsa
    global mutex
    mutex = mutexa
    global thread_file_suffix
    thread_file_suffix = uuid.uuid4()

    if (args.fragmentation_mode == "medchemfrag"):
        os.makedirs(f"./gendata_medchemfrag_output_{thread_file_suffix}")

def handle_row(row) -> tuple[str, drug_fragment_selection]|None:
    _, row = row
    try:
        drug_smiles = row["drug"]
        drug_mol = smiles_to_mol(drug_smiles)
        # print(f"drug weight {Descriptors.MolWt(drug_mol)}")
        if (args.fragmentation_mode == "brics"):
            frags = get_brics_frags_smiles(drug_mol)
            with mutex:
                first = len(fragment_smiles)
                fragment_smiles.extend(frags)
                if len(frags) == 0:
                    print(f"Unable to fragment drug {drug_smiles}")
                else:
                    drug_fragment_pairs.append(drug_fragment_selection(first, len(frags), drug_smiles))
            
        elif args.fragmentation_mode == "recap":
            frags = get_recap_frags_smiles(drug_mol)
            with mutex:
                first = len(fragment_smiles)
                fragment_smiles.extend(frags)
                if len(frags) == 0:
                    print(f"Unable to fragment drug {drug_smiles}")
                else:
                    drug_fragment_pairs.append(drug_fragment_selection(first, len(frags), drug_smiles))
        elif args.fragmentation_mode == "medchemfrag":
            drug_smarts = Chem.rdmolfiles.MolToSmarts(drug_mol, True)
            with open(f"./temp_drug_smarts_{thread_file_suffix}.smi", "w") as smarts_file:
                smarts_file.write(drug_smarts)
            # print("GOT", subprocess.run("dir").stdout)
            result = subprocess.run(f"python3.11 medchem_fragment_splitter.py -l ./temp_drug_smarts_{thread_file_suffix}.smi -a -x -w ./gendata_medchemfrag_output_{thread_file_suffix}/ -o ./gendata_medchemfrag_output_{thread_file_suffix}/f -f smi", capture_output=True, encoding="utf-8", shell=True)
            if len(result.stderr) > 5:
                raise Exception(f"MedChemFrag fragmentation failed: {result.stdout} {result.stderr}")
            frags = []
            for file in glob.glob(f"./gendata_medchemfrag_output_{thread_file_suffix}/*"):
                smiles = open(file).read()
                if len(smiles) == 0:
                    print("Empty fragment file generated by medchemfrag.")
                else:
                    frags.append(smiles)
            with mutex:
                    first = len(fragment_smiles)
                    fragment_smiles.extend(frags)
                    if len(frags) == 0:
                        print(f"Unable to fragment drug {drug_smiles}")
                    else:
                        drug_fragment_pairs.append(drug_fragment_selection(first, len(frags), drug_smiles))

        elif args.fragmentation_mode == "macfrag":
            drug_smarts = Chem.rdmolfiles.MolToSmarts(drug_mol, True)
            with open(f"./temp_drug_smarts_{thread_file_suffix}.smi", "w") as smarts_file: # SMILES also seem to work
                smarts_file.write(drug_smarts)
            # with open("./temp_drug_smiles.smi", "w") as smiles_file: 
                # smiles_file.write(drug_smiles)
            result = subprocess.run(f"python3.11 macfrag_fragment_splitter.py -i ./temp_drug_smarts_{thread_file_suffix}.smi -o ./gendata_macfrag_output_{thread_file_suffix}_ -asMols False -maxBlocks 6 -maxSR 8 -minFragAtoms 8", capture_output=True, encoding="utf-8", shell=True)
            if len(result.stderr) > 5:
                raise Exception(f"MacFrag fragmentation failed: {result.stdout} {result.stderr}")
            # print(open("./gendata_macfrag_output_fragments.smi").read())
            # print(result.stdout)
            # quit()
            with open(f"./gendata_macfrag_output_{thread_file_suffix}_fragments.smi", "r") as file:
                frags = []
                for smiles in file:
                    frags.append(smiles)
                with mutex:
                    first = len(fragment_smiles)
                    fragment_smiles.extend(frags)
                    if len(frags) == 0:
                        print(f"Unable to fragment drug {drug_smiles}")
                    else:
                        drug_fragment_pairs.append(drug_fragment_selection(first, len(frags), drug_smiles))

        # elif args.fragmentation_mode == "fasmifra":
        #     drug_smarts = Chem.rdmolfiles.MolToSmarts(drug_mol, True)
        #     with open("./temp_drug_smarts.smi", "w") as smarts_file:
        #         smarts_file.write(drug_smarts+"\tNAME") #FASMIFRA expects each input molecule to be followed by its name and a tab
        #     result = subprocess.run("python3.11 ../fasmifra/FASMIFRA/bin/fasmifra_fragment.py -n 10 -w 10000 -i ./temp_drug_smarts.smi -o gendata_fasmifra_output.smi", capture_output=True, encoding="utf-8", shell=True)
        #     # if len(result.stderr) > 5:
        #         # raise Exception(f"FASMIFRA fragmentation failed: {result.stdout} {result.stderr}")
        #     with open("./gendata_fasmifra_output.smi", "r") as file:
        #         for smiles in file:
        #             fragment_smiles.append(smiles.split("\t")[0]) # output needs to have "\tNAME" removed from end
        #             # print("GENERATED ", fragment_smiles[len(fragment_smiles)-1])
        else:
            print("Invalid fragmentation mode given.")
            quit()
    except Exception as e:
        print("Exception generated during fragmentation: ", traceback.format_exc())
        print(f"Unable to fragment drug {drug_smiles}")
    

def main():
    # purge old data
    try:
        for file in glob.glob("./gendata_docking_output_dir/*.pdbqt"):
            os.remove(file)
        for file in glob.glob("./gendata_docking_input_dir/*.pdbqt"):
            os.remove(file)
        for file in glob.glob("./gendata_macfrag_output_*"):
            os.remove(file)
        for file in glob.glob("./temp_drug_smarts_*"):
            os.remove(file)
        for dir in glob.glob('./gendata_medchemfrag_output_*/'):
            os.removedirs(dir)
    except Exception as e:
        pass

    parser = argparse.ArgumentParser(description='Drug fragmentation and ranking for FragPredict dataset generation')

    parser.add_argument('--input_csv', type=str, required=True, help='Path to input CSV file with SMILES strings')
    parser.add_argument('--docking_config_path', type=str, required=True, help='Path to JSON with receptor pdbqt path and docking box info')
    parser.add_argument('--output_path', type=str, required=True, help='Output path for the results CSV')
    parser.add_argument('--fragmentation_mode', type=str, required=True, help='options include brics, recap, medchemfrag, macfrag, and fragpredict')
    parser.add_argument("--model_path", type=str, required=False, help="required if using fragmentation mode fragpredict")
    parser.add_argument('--graphs_path', type=str, required=False, help='optional filepath naming where matplotlib graphs will be written to describing selected fragment characteristics. For debug purposes. Don\'t add a file extension.', default=None)
    parser.add_argument('--data_path', type=str, required=False, help='optional filepath to txt where aggregate data about generated fragments will be written. ')

    args = parser.parse_args()

    config_json = None
    with open(args.docking_config_path, "r") as f:
        config_json = f.read()
    docking_config = json.loads(config_json)

    # generate fragments
    csv_data = pandas.read_csv(args.input_csv)

    if args.fragmentation_mode == "fragpredict":
        import torch
        import transformers
        import random
        from transformers import RobertaTokenizer, RobertaForMaskedLM

        fragment_smiles: list[str] = []
        drug_fragment_pairs: list[drug_fragment_selection] = []

        model = RobertaForMaskedLM.from_pretrained(args.model_path)
        tokenizer = RobertaTokenizer.from_pretrained(args.model_path)
        model.eval()

        for _, row in csv_data.iterrows():
            try:
                drug_smiles = row["drug"]
                # for i in range(0, 5):
                # transformers.set_seed(random.randint(0, 1000000))
                inputs = tokenizer(drug_smiles, max_length=128, padding='max_length', truncation=True, return_tensors="pt")
                with torch.no_grad():
                    outputs = model(input_ids=inputs['input_ids'], attention_mask=inputs['attention_mask'])
                logits = outputs.logits
                predicted_ids = torch.argmax(logits, dim=-1)
                predicted_smiles = tokenizer.decode(predicted_ids[0], skip_special_tokens=True)
                # print("MADE FRAGMENT ", predicted_smiles)
                fragment_smiles.append(predicted_smiles)
                drug_fragment_pairs.append(drug_fragment_selection(len(fragment_smiles)-5, 5, drug_smiles))
            except Exception as e:
                print("Drug fragmentation failed for drug smiles ", drug_smiles, " because: ", e, "")
    else:
        # fragment generation is CPU bound so we use multiprocessing to speed it up 
        manager = multiprocessing.Manager()
        fragment_smiles: list[str] = manager.list()
        drug_fragment_pairs: list[drug_fragment_selection] = manager.list()

        mut = multiprocessing.Lock()
        pool = multiprocessing.Pool(6, initializer=setup_process, initargs=[args, fragment_smiles, drug_fragment_pairs, mut])
        pool.map(handle_row, csv_data.iterrows())
        # for _, row in csv_data.iterrows():
            
        pool = None

    # default scoring config used in paper
    s_config = scoring_config()

    scores, extra_frag_data = score_fragments(fragment_smiles, docking_config, s_config)

    results = []

    # (extra data collected for debugging purposes and comparing fragmentation methods) 
    best_scores = []
    docking_scores = []
    ligand_efficiencies = []
    log_s_values = []
    masses = []
    synthetic_accesibilities = []
    aromatic_ring_counts = []
    rotatable_bond_counts = []

    for p in drug_fragment_pairs:
        best_i = -1
        best_score = -math.inf
        for i in range(p.first_fragment_index, p.first_fragment_index + p.num_fragments):
            if scores[i] > best_score:
                best_score = scores[i]
                best_i = i
        if best_i == -1:
            print(f"No fragment for drug {p.drug_smiles} had a suitable score.")
        else:
            results.append({"drug":p.drug_smiles, "fragment": fragment_smiles[best_i], "score" : best_score, "docking_score" : extra_frag_data[best_i].docking_score, "ligand_efficiency" : extra_frag_data[best_i].ligand_efficiency, "predicted_log_s" : extra_frag_data[best_i].log_s, "sascore" : extra_frag_data[best_i].synthetic_accessibility})
            
            # (extra data collected for debugging purposes and comparing fragmentation methods) 
            docking_scores.append(extra_frag_data[best_i].docking_score)
            ligand_efficiencies.append(extra_frag_data[best_i].ligand_efficiency)
            log_s_values.append(extra_frag_data[best_i].log_s)
            masses.append(extra_frag_data[best_i].mass**2 / 400)
            synthetic_accesibilities.append(extra_frag_data[best_i].synthetic_accessibility)
            rotatable_bond_counts.append(extra_frag_data[i].num_rotatable_bonds)
            aromatic_ring_counts.append(extra_frag_data[best_i].num_aromatic_rings)
            best_scores.append(best_score)

    results_df = pandas.DataFrame(list(results))
    results_df.to_csv(args.output_path, index=False)

    print("Successfully generated data for ", len(results), " fragment-drug pairs out of ", csv_data.__len__())

    # (extra data collected for debugging purposes and comparing fragmentation methods) 
    if args.data_path:
        with open(args.data_path, "a") as f:
            f.write(f"FOR FRAGMENTATION MODE {args.fragmentation_mode}:\n")
            f.write(f"\tSelected fragment mean mass: {sum_skip_none(masses)/float(len_skip_none(masses))}\n")
            f.write(f"\tSelected fragment mean binding affinity: {sum_skip_none(docking_scores)/float(len_skip_none(docking_scores))}\n")
            f.write(f"\tSelected fragment mean ligand efficiency: {sum_skip_none(ligand_efficiencies)/float(len_skip_none(ligand_efficiencies))}\n")
            f.write(f"\tSelected fragment mean logS: {sum_skip_none(log_s_values)/float(len_skip_none(log_s_values))}\n")
            f.write(f"\tSelected fragment mean SAscore: {sum_skip_none(synthetic_accesibilities)/float(len_skip_none(synthetic_accesibilities))}\n")
            f.write(f"\tSelected fragment mean fragment score: {sum_skip_none(best_scores)/float(len_skip_none(best_scores))}\n")
            f.write(f"\tSelected fragment mean #aromatic rings: {sum_skip_none(aromatic_ring_counts)/float(len_skip_none(aromatic_ring_counts))}\n")
            f.write(f"\tSelected fragment mean #rotatable bonds: {sum_skip_none(rotatable_bond_counts)/float(len_skip_none(rotatable_bond_counts))}\n")
            # f.write(f"\tAll fragments means fragment score: {sum_skip_none(scores)/float(len_skip_none(scores))}\n")

    # graphs used for debugging purposes
    if args.graphs_path:
        plt.scatter(x=docking_scores, y=log_s_values, s=masses)
        # plt.scatter(x=docking_scores, y=synthetic_accesibilities, s=masses)
        # plt.scatter(x=aromatic_ring_counts, y=rotatable_bond_counts)
        # plt.xlabel("AROMATIC")
        # plt.ylabel("ROTATABLE")
        plt.xlabel("Binding affinity")
        plt.ylabel("Predicted logS")
        # plt.ylabel("SAscore (synthetic accessibility)")
        plt.savefig(args.graphs_path+"_1.png")
        print("Wrote matplotlib graphs to " + args.graphs_path + "_1.png")

if __name__ == "__main__":
    main()
